kind:                           Secret
apiVersion:                     v1

metadata:
  name:                         ejemplo-secret

# Es un conjunto de datos CLAVE VALOR
data: # No lleva spec (Namespace, configmap y secret son los unicos documentos yaml de kubernetes que no tienen spec)
  contraseña-root:              TWlzdXBlcnBhc3N3b3Jk #Misuperpassword # base64
  contraseña-usuario:           bWlwYXNzd29yZDI= # base64

# Esto no da seguridad 
# base 64 es solo una codificación (como un juego de carácteres)

# Solución real: 
# Estos archivos NO SE CREAN!
# o mejor dicho: NO LOS CREAMOS NOSOTROS

# Los secrets se crean desde el cliente 
# `kubectl create secret generic ejemplo-secret --from-literal=contraseña-root=Misuperpassword --from-literal=contraseña-usuario=mipassword2`
# Ese comando genera internamente el archivo yaml y lo carga en kubernetes.
# El archivo dentro de la BBDD de kubernetes se guarda encriptado...
# Esa es la diferencia de los secrets.. el tratamiento interno que kubernetes hace del fichero.

# Muchas veces, ese comando SE GENERA BAJO DEMANDA 
#por un pipeline de CD (Continuous Deployment) y los valores se sacan de lo que llamamos un VAULT.